name: waiting_indicator
description: Handle waiting/error handling while calling functions.
repository: https://github.com/devobs/waiting_indicator
homepage: https://github.com/devobs
version: 0.0.1


environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
